version: "3.9"
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend.techchallenge.api:dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_ENVIRONMENT: Development      
    ports:
      - "5055:80"